# analysis_options.yaml
# Flutter project configuration optimized for performance, immutability, and readability
# Ensures trailing commas, const usage, and fast widget tree rendering

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # -------------------------------
    # Style / Formatting
    # -------------------------------
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    require_trailing_commas: true               # Keep trailing commas in multi-line widgets/lists
    sort_child_properties_last: true            # Flutter style: child properties last
    prefer_single_quotes: true
    unnecessary_string_escapes: true

    # -------------------------------
    # Const / Immutability / Performance
    # -------------------------------
    prefer_const_constructors: true             # Use const widgets wherever possible
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true             # Const for variables where possible
    prefer_final_fields: true                   # Immutable class fields
    prefer_final_locals: true                   # Immutable local variables
    prefer_const_constructors_in_immutables: true
    immutable: true                             # All widget classes should be immutable
    avoid_unnecessary_containers: true          # Reduce widget tree depth
    use_key_in_widget_constructors: true        # Helps Flutter identify widgets

    # -------------------------------
    # Null Safety / Type Safety
    # -------------------------------
    always_specify_types: true
    annotate_overrides: true
    prefer_typing_uninitialized_variables: true
    avoid_init_to_null: true
    avoid_dynamic_calls: true

    # -------------------------------
    # Readability / Maintainability
    # -------------------------------
    avoid_print: true                            # Use debugPrint or logger
    lines_longer_than_80_chars: false           # Allow longer lines for widget trees
    prefer_final_in_for_each: true
    prefer_collection_literals: true
    avoid_redundant_argument_values: true
    avoid_function_literals_in_foreach_calls: true

# -------------------------------
# Analyzer Settings
# -------------------------------
analyzer:
  strong-mode:
    implicit-casts: false                      # Prevent hidden type conversions
    implicit-dynamic: false                    # Avoid dynamic types
  exclude:
    - build/**
    - ios/Pods/**
    - android/.gradle/**